include:
  - project: 'platform-one/big-bang/pipeline-templates/pipeline-templates'
    ref: pipeline-nonibimages
    file: '/templates/package-tests.yml'
variables:
  DEPENDENCY_REPO: "https://repo1.dsop.io/platform-one/big-bang/apps/core/istio-operator.git"
  DEPENDENCY_REPO_BRANCH: main
  ISTIO_GATEWAY_NS: istio-system
  PROJECT_NAME: istio-system
  ADD_DEPENDENCY_NAMESPACE: istio-operator
   
